api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      # 80-->443 redirect for all
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: ":443"
    # The {} is necessary
    http3: {}
    http:
      middlewares:
        - secureHeaders@file

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/etc/traefik"
    watch: true

certificatesResolvers:
  le-home:
    acme:
      dnsChallenge:
        provider: cloudflare
      email: "EMAIL"
      storage: "/etc/traefik/acme.json"
      certificatesduration: 2160

experimental:
  plugins:
    sablier:
      moduleName: "github.com/acouvreur/sablier"
      version: "v1.7.0"

# log:
#   level: DEBUG

#accessLog: {}