#sensors.yaml
andrew_covid_test_result: https://labtools.curativeinc.com/api/v1/appointments/get_by_access_token/token
andrew_birthday: '{"dob":"2013-09-17"}'
bethany_covid_test_result: https://labtools.curativeinc.com/api/v1/appointments/get_by_access_token/token
bethany_birthday: '{"dob":"2013-09-17"}'
domain_2_name: domain2.fako.com Certificate Expiry
domain_2: domain2.fako.com
darksky_api_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
usps_username: user
usps_key: key
fedex_username: user
fedex_password: key
ups_username: user
ups_password: key
17track_user: user
17track_pass: password

#configuration.yaml
amcrest_password: password
go2rtc_base_url: "https://phony.com/api/"
go2rtc_frontdoor_url: "https://phony.com/api/frame.jpeg?src=front_door_fullres"
AzureSpeechKey: XXXXXXXXXXX
hass_url: https://not_really_it.com
elevation: 60000
home_lat: 00.00
home_long: 00.00
andrew_work_lat: 00.00
andrew_work_long: 00.00
bethany_work_lat: 00.00
bethany_work_long: 00.00
configurator_url: https://www.home-assistant.io/docs/ecosystem/hass-configurator/
vscode_url: https://community.home-assistant.io/t/install-vscode-visual-studio-code-as-a-separate-docker-container/166007/27
dan_lat: 00.00
dan_long: 00.00
external_url: https://google.com
frontdoor_url: https://google.com
ewelink_user: secret@fako.com
ewelink_pass: PASS
github_recipes_webhook: lolsecret
wayne_lat: 00.00
wanye_long: 00.00
michael_lat: 00.00
michael_long: 00.00
travis_lat: 00.00
travis_long: 00.00
plane: https://en.wikipedia.org/wiki/Automatic_dependent_surveillance_%E2%80%93_broadcast
plane2: https://en.wikipedia.org/wiki/Automatic_dependent_surveillance_%E2%80%93_broadcast
nodered: https://nodered.org
grafana: https://grafana.com
esphome: https://esphome.io
portainer: https://www.portainer.io
api_password: key
owntracks_user: user
owntracks_password: key
plex_token: token
plex_user: user
plex_password: password
openweather: API_KEY
amazon_email: EMAIL@FAKO.COM
amazon_pass: PASSWORD
spotify_client_id: id
spotify_client_secret: secret
secure_devices_pin: "1234"
signal_phone: "+10000000000"
signal_phone_andrew: "+10000000000"
signal_group_bvst: "group.id"
signal_group_bvst_ins: "group.id"
signal_group_adsb: "group.id"
signal_group_frigate: "group.id"
signal_group_homeassistant: "group.id"
tile_user: user
tile_password: password
pfsense_json_key: secret
pushbullet_key: XXXXXXXXXXXXXXXXXXXXXXXXXX
pushover_api_key: XXXXXXXXXXXXXXXXXXXXXXX
pushover_user_key: XXXXXXXXXXXXXXXXXXXX
vapid_pub_key: really_public_key
vapid_prv_key: really_private_key
vapid_email: fake_email@fake.com
influx_user: user
influx_password: password
IFTTT: XXXX
yahoo_woeid: XXXXXXXXXX
alexa_client_id: PHONY
alexa_client_secret: PHONY
haveibeenpwned_1: EMAIL
haveibeenpwned_2: EMAIL
haveibeenpwned_3: EMAIL
haveibeenpwned_4: EMAIL
haveibeenpwned_5: EMAIL
haveibeenpwned_6: EMAIL
netatmo_key: KEY
netatmo_secret: SECRET
netatmo_lat_ne: 31
netatmo_lon_ne: -92
netatmo_lat_sw: 31
netatmo_lon_sw: -96
DO_token: TOKEN
DO_host: HOST
rtorrent: "https://myuser:reallylegitpassword@reallyfake.com:443/RPC"
roborock_token: d41d8cd98f00b204e4400998ec111111
stock_one: "AAPL"
utilities_curl_summary: "exit"
utilities_curl_daily: "exit"
utilities_curl_realtime: "exit"
utilities_curl_start: "exit"
utilities_curl_end: "exit"
utilities_account_curl: "exit"
utilities_rest_url: https://www.com
utilities_rest_payload: Account=12345678
utility_bill_url: https://www.com
utility_bill_url_payload: '{"payload":{"accountId":"account"},"username":"user"}'
ocx_tenant_id: tenant
utility_bill_amount_url: https://www.com


xbox_id: 1
xbox_secret: s
zoom_webhook: zoomzoom

#camera.yaml
weather_url: https://fako.com/weather

#groups.yaml

#ui-lovelace.yaml
windy_url: https://embed.windy.com/embed2.html?rain
domain_1_expiry_sensor: sensor.domainfakocom
domain_2_expiry_sensor: sensor.domain2fakocom

#automation.yaml
cf_lock_otp_webhook: SECRETURL
mom_and_dad_garage_webhook_id: SECRET_URL
mom_and_dad_gate_webhook_id: SECRET_URL
github_token: GITHUB_KEY
panic_script_webhook: somethingsecret
# need to full url with secret hook for pushover
panic_script_webhook_full: https://my-actual-domain.rocks/api/webhook/somethingsecret
bluebubbles_server_update_webhook: secret_webhook
signal_bvst_contact_webhook_id: secret_webhook
signal_bvst_intake_webhook_id: secret_webhook
signal_bvst_insurance_webhook_id: secret_webhook
cellular_modem_power_toggle_webhook: secret_webook
cellular_message_test_webook: secret_webhook
terraform_cloud_webhook: secret_webhook
teslausb_webhook: secret_webhook

#packages
cf_otp_webhook_gate: SECRETURL
cf_otp_webhook_garage: SECRETURL
hass_github_action_webhook: SECRET
garage_image_url: https://FQDN/local/cameras/garage_latest.jpg
xiaomi_cloud_username: user
xiaomi_cloud_password: password
andrew_webhook: hooky
teslamate-frontend: https://teslamate.fake.domain
