# Common settings to all my devices
wifi:
  ssid: "SSID"
  password: !secret wifi_password

logger:
  level: DEBUG

api:
  #reboot_timeout: 0s # default is 15m
  encryption:
    key: !secret encryption_key

ota:
  platform: esphome
  password: esphome_recovery

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"