substitutions:
  name: d1_sht_1
  friendly_name: "D1 SHT 1"

esphome:
  name: ${name}

esp8266:
  board: d1_mini

<<: !include common.yaml
  
i2c:
  sda: D2
  scl: D1
  scan: False
  
sensor:
  - platform: template
    name: "${friendly_name} Temperature"
    unit_of_measurement: "°F"
    lambda: |-
      // Convert Celsius to Fahrenheit
      float f = id(temp_c).state * (9.0/5.0) + 32.0;
      // Truncate to 2 decimals
      return int(f * 100.0) / 100.0;
  - platform: sht3xd
    temperature:
      id: temp_c
    humidity:
      name: "${friendly_name} Humidity"
      accuracy_decimals: 2
      filters:
        - round: 2
    address: 0x45
    update_interval: 60s

switch:
  - platform: restart
    id: restart_device
    name: "${friendly_name} Restart"