substitutions:
  name: door_sensor
  friendly_name: "Door Sensor"

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini

<<: !include common.yaml

# See https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/ for
# allowable pins

time:
  - platform: homeassistant
    id: homeassistant_time

datetime:
  - platform: template
    id: front_door_last
    type: datetime
    name: Front Door Last
    optimistic: yes
    restore_value: true

  - platform: template
    id: master_bedroom_exterior_door_last
    type: datetime
    name: Master Bedroom Exterior Door Last
    optimistic: yes
    restore_value: true

  - platform: template
    id: back_porch_door_last
    type: datetime
    name: Back Porch Door Last
    optimistic: yes
    restore_value: true

  - platform: template
    id: garage_interior_door_last
    type: datetime
    name: Garage Interior Door Last
    optimistic: yes
    restore_value: true

  - platform: template
    id: garage_exterior_door_last
    type: datetime
    name: Garage Exterior Door Last
    optimistic: yes
    restore_value: true

binary_sensor:
  - platform: gpio
    pin:
      mode: INPUT_PULLUP
      number: D1
    name: "Front Door"
    device_class: door
    filters:
      - delayed_on_off: 0.5s
    on_press:
      then:
        - datetime.datetime.set:
            id: front_door_last
            datetime: !lambda |-
              return id(homeassistant_time).now();

  - platform: gpio
    pin:
      mode: INPUT_PULLUP
      number: D2
    name: "Master Bedroom Exterior Door"
    device_class: door
    filters:
      - delayed_on_off: 0.5s
    on_press:
      then:
        - datetime.datetime.set:
            id: master_bedroom_exterior_door_last
            datetime: !lambda |-
              return id(homeassistant_time).now();

  - platform: gpio
    pin:
      mode: INPUT_PULLUP
      number: D5
    name: "Back Porch Door"
    device_class: door
    filters:
      - delayed_on_off: 0.5s
    on_press:
      then:
        - datetime.datetime.set:
            id: back_porch_door_last
            datetime: !lambda |-
              return id(homeassistant_time).now();

  - platform: gpio
    pin:
      mode: INPUT_PULLUP
      number: D6
    name: "Garage Interior Door"
    device_class: door
    filters:
      - delayed_on_off: 0.5s
    on_press:
      then:
        - datetime.datetime.set:
            id: garage_interior_door_last
            datetime: !lambda |-
              return id(homeassistant_time).now();

  - platform: gpio
    pin:
      mode: INPUT_PULLUP
      number: D7
    name: "Garage Exterior Door"
    device_class: door
    filters:
      - delayed_on_off: 0.5s
    on_press:
      then:
        - datetime.datetime.set:
            id: garage_exterior_door_last
            datetime: !lambda |-
              return id(homeassistant_time).now();

switch:
  - platform: restart
    id: restart_device
    name: "${friendly_name} Restart"

  # GPIO output for relay
  - platform: gpio
    id: relay
    icon: "mdi:alarm-bell"
    name: "Attic Siren"
    pin:
      number: D8
      inverted: False
    on_turn_on:
      # Sound siren for max 5 minutes
      - delay: 300s
      - switch.turn_off: relay