substitutions:
  name: kitchen_water_detector
  friendly_name: "Kitchen Water Detector"

esphome:
  name: ${name}

esp8266:
  board: d1_mini

<<: !include common.yaml

binary_sensor:
  - platform: gpio
    pin:
      mode: INPUT_PULLUP
      inverted: True
      number: D2 # D2 - GND
    name: "${friendly_name}"
    device_class: moisture
    filters:
      - delayed_on_off: 0.5s

switch:
  - platform: restart
    id: restart_device
    name: "${friendly_name} Restart"