substitutions:
  name: kitchen_table_leds
  friendly_name: "Kitchen Table LEDs"

esphome:
  name: ${name}

esp8266:
  board: esp01_1m
  restore_from_flash: true

<<: !include common.yaml

light:
  - platform: rgb
    name: "Kitchen Table LEDs"
    red: red_channel
    green: green_channel
    blue: blue_channel

output:
  - platform: esp8266_pwm
    id: red_channel
    pin: GPIO5
  - platform: esp8266_pwm
    id: blue_channel
    pin: GPIO13
  - platform: esp8266_pwm
    id: green_channel
    pin: GPIO12