substitutions:
  name: kmc_multi_plug_1
  friendly_name: "KMC Multi Plug 1"
  
esphome:
  name: ${name}

esp8266:
  board: esp01_1m
  restore_from_flash: true

<<: !include common.yaml

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: 'America/Chicago'
    on_time:
      # Aquarium CO2 ON at 07:00:00
      - seconds: 0
        minutes: 0
        hours: 7
        then:
          - switch.turn_on: relay1
          - logger.log: "CO2 Solenoid Engaged"

      # Aquarium CO2 OFF at 16:30:00
      - seconds: 0
        minutes: 30
        hours: 16
        then:
          - switch.turn_off: relay1
          - logger.log: "CO2 Solenoid Disengaged"

sensor:
  - platform: hlw8012
    sel_pin: GPIO12
    cf_pin: GPIO4
    cf1_pin: GPIO5
    # current:
    #   name: "${friendly_name} Current"
    # voltage:
    #   name: "${friendly_name} Voltage"
    power:
      name: "${friendly_name} Power"
      id: my_power_sensor
    update_interval: 30s

# Add this section for Energy Consumption
  - platform: total_daily_energy
    name: "${friendly_name} Total Daily Energy"
    power_id: my_power_sensor
    unit_of_measurement: kWh
    accuracy_decimals: 2
    filters:
      # Multiplication factor to convert W to kWh
      - multiply: 0.001

switch:
  - platform: gpio
    name: "${friendly_name} 1" # CO2
    pin: GPIO15
    id: relay1
  - platform: gpio
    name: "${friendly_name} 2" # Filter
    pin: GPIO13
    id: relay2
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: "${friendly_name} 3" # Light
    pin: GPIO14
    id: relay3
    restore_mode: ALWAYS_ON

  - platform: restart
    id: restart_device
    name: "${friendly_name} Restart"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      mode: INPUT_PULLDOWN
      inverted: True
    name: "${friendly_name} Button"
    on_press:
      - switch.toggle: relay2
    # on_double_click:
    #   min_length: 50ms
    #   max_length: 350ms
    #   then:
    #   - switch.turn_off: relay1
    #   - switch.turn_off: relay2
    #   - switch.turn_off: relay3

status_led:
  pin:
    number: GPIO1
    inverted: yes