substitutions:
  name: power_plug_2
  friendly_name: "Xbox"
  # Higher value gives lower watt readout
  current_res: "0.00221"
  # Lower value gives lower voltage readout
  voltage_div: "955"
  
esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m

<<: !include common.yaml

sensor:
  # Power measuring sensor
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO5
    cf1_pin: GPIO14
    power:
      id: power
      name: "xbox power"
      filters:
        # Some calibration
        - multiply: 0.4545
        - sliding_window_moving_average:
            window_size: 15
            send_every: 2
    current_resistor: 0.001  # default 0.001
    voltage_divider: 910     # default 2351
    change_mode_every: 3     # default 8
    update_interval: 1s      # default 60s

# Enable getting local time for total daily energy calculation
time:
  - platform: homeassistant
    id: homeassistant_time

status_led:
  pin:
    number: GPIO0   # Red LED
    inverted: True

binary_sensor:
  # - platform: gpio
  #   pin: GPIO13
  #   id: button
  #   on_press:
  #     - switch.toggle: relay
  #   internal: True

  - platform: template
    name: "${friendly_name} Power"
    device_class: occupancy
    lambda: if (id(power).state > 15) return true; else return false;

switch:
  - platform: gpio
    id: blue_led
    pin:
      number: GPIO2
      inverted: True
    
  - platform: gpio
    pin: GPIO4
    id: relay
    restore_mode: ALWAYS_ON
    #name: "${friendly_name}"
    # Tie Blue LED to relay
    on_turn_on:
    - switch.turn_on: blue_led
    on_turn_off:
    - switch.turn_off: blue_led
    
  - platform: restart
    id: restart_device
    name: "${friendly_name} Restart"