# =============================================================================
# HARDWARE INFORMATION
# =============================================================================
# ESP32 Chip: ESP32-S3 rev0.2, 2 core(s)
# ESP32-S3-DevkitC-1 V1.0
# Onboard LED -> GPIO48
# =============================================================================
  
# =============================================================================
# Basic ESPHome configurations
# =============================================================================
# Core board ESP32-S3-DevkitC-1
# Lgger, OTA, Fallback hotpot and PSRAM enabled
# By default of PlatformIO, board: esp32-s3-devkitc-1 means for a non-PSRAM version.
# "platformio_options" must be defined to overwrite the default options of the board,
# to give right confirmation for N16R8
# =============================================================================

substitutions:
  name: "sendspin-main"
  friendly_name: "SendSpin Main"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  variant: esp32s3
  board: esp32-s3-devkitc-1
  cpu_frequency: 240MHz
  flash_size: 16MB
  toolchain: esp-idf  
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_ENABLED: "n"                     # Keep this to free up RAM/CPU from Bluetooth
      CONFIG_ESP_WIFI_TASK_CORE_ID: "0"          # Keep if you specifically want Wi-Fi pinned to core 0
      CONFIG_ESP_WIFI_IRAM_OPT: "y"              # Moves Wi-Fi high-performance code to ultra-fast IRAM
      CONFIG_ESP_WIFI_RX_BA_WIN: "16"            # Increases Wi-Fi Block Ack RX window size for smoother TCP/UDP streams

# Enable logging
logger:
  level: DEBUG
  logs:
    sensor: WARN 

ota:
  platform: esphome
  password: esphome_recovery

# Wifi setup
wifi:
  ssid: "SSID"
  password: !secret wifi_password
  power_save_mode: NONE

network:
  enable_high_performance: true

# Mandatory for ESP32-S3 modules with 8MB/16MB PSRAM
psram:
  mode: octal
  speed: 80MHz
  ignore_not_found: false

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

  reboot_timeout: 0s

# # Enable http request
# http_request:
#   buffer_size_rx: 4096

# Sendspin related components are pinned to specific commits for reproducible builds
#external_components:
  # - source:
  #     # https://github.com/esphome/esphome/pull/14933
  #     type: git
  #     url: https://github.com/kahrendt/esphome
  #     ref: 7a6cf5c8472b7e2fa18ee0fc314f66a80d249e32
  #   components: [const, media_source, sendspin]
  # - source:
  #     # https://github.com/esphome/esphome/pull/14933
  #     type: git
  #     url: https://github.com/esphome/esphome
  #     ref: dev
  #   refresh: 0s
  #   components: [const, media_source, sendspin]
  # - source:
  #     # https://github.com/esphome/esphome/pull/12429
  #     type: git
  #     url: https://github.com/esphome/esphome
  #     ref: ff8ce89556748509d7ee8724e12d9d43d3c8c1e8
  #   refresh: 0s
  #   components: [http_request]

# =============================================================================
# Media player / I2S configurations
# =============================================================================
# At sample rate 44100Hz, 2 channels, 16bit, every 1ms buffer uses about 176.4 Bytes
# 100ms - 17.64K, 200ms - 35.2KB, 500ms # Increased from 100 5/16 - 86.13KB
# If no sound by setting bits_per_sample to 32bit, set to 16bit instead
# =============================================================================
i2s_audio:
  - id: i2s_out
    i2s_lrclk_pin: GPIO15
    i2s_bclk_pin: GPIO17

speaker:
  - platform: i2s_audio
    id: i2s_audio_speaker
    i2s_audio_id: i2s_out
    sample_rate: 48000
    i2s_dout_pin: GPIO16
    bits_per_sample: 16bit
    dac_type: external
    channel: stereo
    timeout: never
    buffer_duration: 100ms # Increased from 100 5/16 # Increased from 100 5/16

  - platform: mixer
    id: mixer_speaker_id
    output_speaker: i2s_audio_speaker
    source_speakers:
      - id: media_spk_mixer_input
        buffer_duration: 100ms # Increased from 100 5/16
        timeout: never
      - id: announcement_spk_mixer_input
        buffer_duration: 100ms # Increased from 100 5/16
        timeout: never
    num_channels: 2
    task_stack_in_psram: true

  - platform: resampler
    id: media_resampling_speaker
    output_speaker: media_spk_mixer_input
    sample_rate: 48000
    bits_per_sample: 16
    buffer_duration: 100ms # Increased from 100 5/16
    task_stack_in_psram: true
  - platform: resampler
    id: announcement_resampling_speaker
    output_speaker: announcement_spk_mixer_input
    sample_rate: 48000
    bits_per_sample: 16
    buffer_duration: 100ms # Increased from 100 5/16
    task_stack_in_psram: true

sendspin:
  id: sendspin_hub
  task_stack_in_psram: true # troubleshooting set to true

media_source:
  - platform: audio_http
    id: http_announcement_source
    buffer_size: 250000
  - platform: audio_http
    id: http_media_source
    buffer_size: 500000
  - platform: sendspin
    id: sendspin_media_source

media_player:
  - platform: sendspin
    id: sendspin_group_media_player
  - platform: speaker_source
    name: ${friendly_name}
    id: external_media_player
    internal: false
    media_pipeline:
        speaker: media_resampling_speaker
        format: FLAC # troubleshooting set from MP3
        sample_rate: 48000
        num_channels: 2
        sources:
          - http_media_source
          - sendspin_media_source
    announcement_pipeline:
        speaker: announcement_resampling_speaker
        format: FLAC # troubleshooting set from MP3
        sample_rate: 48000
        num_channels: 1
        sources:
          - http_announcement_source
    volume_increment: 0.02
    volume_initial: 0.20
    volume_min: 0.05
    volume_max: 0.95
    on_announcement:
      - mixer_speaker.apply_ducking:
          id: media_spk_mixer_input
          decibel_reduction: 20
          duration: 0.0s
    on_state:
      if:
        condition:
          not:
            media_player.is_announcing: external_media_player
        then:
          - mixer_speaker.apply_ducking:
              id: media_spk_mixer_input
              decibel_reduction: 0
              duration: 1.0s

switch:
  - platform: restart
    id: restart_device
    name: "${friendly_name} Restart"
