substitutions:
  friendly_name: "Sonoff Pow"

esphome:
  name: sonoff_pow

esp8266:
  board: esp01_1m
  board_flash_mode: dout

<<: !include common.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: False
    name: ${friendly_name} Reed Switch
    on_press:
      then:
        - switch.turn_on: relay
        - delay: 30min
        - switch.turn_off: relay
    on_release:
      then:
        - switch.turn_off: relay

sensor:
  - platform: hlw8012
    sel_pin: 5
    cf_pin: 14
    cf1_pin: 13
    update_interval: 60s
    current:
      name: ${friendly_name} Current
    voltage:
      name: ${friendly_name} Voltage
    power:
      name: ${friendly_name} Power
      id: power

switch:
  - platform: template
    name: ${friendly_name} Relay
    optimistic: true
    turn_on_action:
      - switch.turn_on: relay
      #- light.turn_on: led
    turn_off_action:
      - switch.turn_off: relay
      #- light.turn_off: led
  - platform: gpio
    id: relay
    pin: GPIO12

output:
  - platform: esp8266_pwm
    id: pow_blue_led
    pin:
      number: GPIO15
      inverted: False

# light:
#   - platform: monochromatic
#     name: ${friendly_name} Blue LED
#     output: pow_blue_led
#     id: led