substitutions:
  name: water_meter_s2
  friendly_name: "Water Meter S2"
  volume_unit: 'gal'
  i2c_scl: GPIO35  # D1
  i2c_sda: GPIO33  # D2
  prefix_name: s2
  #flow_update_interval_seconds: "5"
  hide_magnetic_field_strength_sensors: 'true'
  hide_half_rotations_total_sensor: 'false'

esphome:
  name: ${name}

# python3 -m esptool -p /dev/cu.usbmodem01 write_flash 0x0 /Users/aneisch/Desktop/XXXXXX.bin
esp32:
  board: lolin_s2_mini
  #type: esp-idf
  # framework:
  #   type: esp-idf
  #   sdkconfig_options:
  #     CONFIG_ESP_CONSOLE_USB_CDC: y

# Common settings to all my devices
wifi:
  ssid: "SSID"
  password: !secret wifi_password

api:
  #reboot_timeout: 0s # default
  encryption:
    key: !secret encryption_key

ota:
  platform: esphome
  password: esphome_recovery

<<: !include water_meter_master.yaml