substitutions:
  name: water_supply
  friendly_name: "Water Supply"

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini
  esp8266_restore_from_flash: yes

<<: !include common.yaml

one_wire:
  platform: gpio
  pin: D4

switch:
  - platform: restart
    id: restart_device
    name: "${friendly_name} Restart"

sensor:
  - platform: dallas_temp
    address: 0xe73de1e38099b628
    name: "${friendly_name} Temperature"