#  SPDX-License-Identifier: Apache-2.0
api:
  name: Run API Command
  # Description of the service
  description: Run an API command using controller.api. https://teslajsonpy.readthedocs.io/en/latest/teslajsonpy/teslajsonpy.html#teslajsonpy.Controller.api
  # Different fields that your service accepts
  fields:
    # Key of the field
    email:
      # Description of the field
      description: Email address (optional if only one account)
      # Example value that can be passed for this field
      example: "elon@tesla.com"
      required: false
      selector:
        text:
    command:
      # Description of the field
      description: Command to run. See https://github.com/zabuldon/teslajsonpy/blob/master/teslajsonpy/endpoints.json
      # Example value that can be passed for this field
      example: "WAKE_UP"
      required: true
      selector:
        text:
    parameters:
      # Description of the field
      description: Parameters in a dictionary. `path_vars` replace variables in endpoints.json path. All others are passed directly to controller.api. For command parameters see https://tesla-api.timdorr.com/vehicle/commands.
      # Example value that can be passed for this field
      example: '{"path_vars": {"vehicle_id":"1"}, "wake_if_asleep":True}'
      required: true
      selector:
        object:

polling_interval:
  name: Set Polling Interval
  description: Set polling interval for updating fresh data from an awake car
  fields:
    email:
      # Description of the field
      description: Email address (optional if only one account)
      # Example value that can be passed for this field
      example: "elon@tesla.com"
      required: false
      selector:
        text:
    vin:
      # Description of the field
      description: Vehicle VIN (if not provided then default polling interval will be updated)
      # Example value that can be passed for this field
      example: "5YJSA11111111111"
      required: false
      selector:
        text:
    scan_interval:
      description: Number of seconds between each poll.  See https://github.com/alandtse/tesla/wiki/Polling-policy more information.
      example: 660
      required: true
      default: 660
      selector:
        number:
          min: -1
          max: 3600
          step: 30
          unit_of_measurement: "s"
