homeassistant:
  customize:
    guest_bedroom_blinds:
      assumed_state: true
    dining_room_blinds:
      assumed_state: true
    office_blinds:
      assumed_state: true

group:
  dining_room_blinds:
    name: Dining Room Blinds
    entities:
      - cover.dining_room_blind_left
      # Start Christmas
      # Comment center for Christmas
      - cover.dining_room_blind_center
      # End Christmas
      - cover.dining_room_blind_right
  guest_bedroom_blinds:
    name: Guest Bedroom Blinds
    entities:
      - cover.guest_bedroom_blind_left
      - cover.guest_bedroom_blind_right
  office_blinds:
    name: Office Blinds
    entities:
      # Start Christmas
      # Comment left for Christmas
      - cover.office_blind_left
      # End Christmas
      - cover.office_blind_right
  master_bedroom_blinds:
    name: Master Bedroom Blinds
    entities:
      - cover.master_bedroom_blind_left
      - cover.master_bedroom_blind_right

template:
  - cover:
    - open_cover:
      - action: script.blinds_group
        data:
          modus: open
          group: guest_bedroom
      close_cover:
      - action: script.blinds_group
        data:
          modus: close
          group: guest_bedroom
      stop_cover:
      - action: script.blinds_group
        data:
          modus: stop
          group: guest_bedroom
      default_entity_id: cover.guest_bedroom_blinds
      icon: "{% if is_state('sensor.guest_bedroom_blinds', 'open') %}\n  mdi:window-open\n{%
        else %}\n  mdi:window-closed\n{% endif %}"
      name: Guest Bedroom Blinds
      state: '{{is_state(''sensor.guest_bedroom_blinds'', ''open'')}}'

    - open_cover:
      - action: script.turn_on
        target:
          entity_id:
          - script.blinds_group
        data:
          variables:
            modus: open
            group: master_bedroom
      close_cover:
      - action: script.turn_on
        target:
          entity_id:
          - script.blinds_group
        data:
          variables:
            modus: close
            group: master_bedroom
      stop_cover:
      - action: script.turn_on
        target:
          entity_id:
          - script.blinds_group
        data:
          variables:
            modus: stop
            group: master_bedroom
      default_entity_id: cover.master_bedroom_blinds
      icon: "{% if is_state('sensor.master_bedroom_blinds', 'open') %}\n  mdi:window-open\n{%
        else %}\n  mdi:window-closed\n{% endif %}"
      name: Master Bedroom Blinds
      state: '{{is_state(''sensor.master_bedroom_blinds'', ''open'')}}'

    - open_cover:
      - action: script.blinds_group
        data:
          modus: open
          group: office
      close_cover:
      - action: script.blinds_group
        data:
          modus: close
          group: office
      stop_cover:
      - action: script.blinds_group
        data:
          modus: stop
          group: office
      default_entity_id: cover.office_blinds
      icon: "{% if is_state('sensor.office_blinds', 'open') %}\n  mdi:window-open\n{%
        else %}\n  mdi:window-closed\n{% endif %}"
      name: Office Blinds
      state: '{{is_state(''sensor.office_blinds'', ''open'')}}'

    - open_cover:
      - action: script.blinds_group
        data:
          modus: open
          group: dining_room
      close_cover:
      - action: script.blinds_group
        data:
          modus: close
          group: dining_room
      stop_cover:
      - action: script.blinds_group
        data:
          modus: stop
          group: dining_room
      default_entity_id: cover.dining_room_blinds
      icon: "{% if is_state('sensor.dining_room_blinds', 'open') %}\n  mdi:window-open\n{%
        else %}\n  mdi:window-closed\n{% endif %}"
      name: Dining Room Blinds
      state: '{{is_state(''sensor.dining_room_blinds'', ''open'')}}'

  - sensor:
    - default_entity_id: sensor.guest_bedroom_blinds
      state: "{% if is_state('cover.guest_bedroom_blind_left', 'open') %}\n  open\n{%
        elif is_state('cover.guest_bedroom_blind_right', 'open') %}\n  open\n{% else
        %}\n  closed\n{% endif %}"
      name: guest_bedroom_blinds

    - default_entity_id: sensor.master_bedroom_blinds
      state: "{% if is_state('cover.master_bedroom_blind_left', 'open') %}\n  open\n{%
        elif is_state('cover.master_bedroom_blind_right', 'open') %}\n  open\n{% else
        %}\n  closed\n{% endif %}"
      name: master_bedroom_blinds

    - default_entity_id: sensor.office_blinds
      state: "{% if is_state('cover.office_blind_left', 'open') %}\n  open\n{% elif
        is_state('cover.office_blind_right', 'open') %}\n  open\n{% else %}\n  closed\n{%
        endif %}"
      name: office_blinds

    - default_entity_id: sensor.dining_room_blinds
      state: "{% if is_state('cover.dining_room_blind_left', 'open') %}\n  open\n{%
        elif is_state('cover.dining_room_blind_center', 'open') %}\n  open\n{% elif
        is_state('cover.dining_room_blind_right', 'open') %}\n  open\n{% else %}\n  closed\n{%
        endif %}"
      name: dining_room_blinds

input_boolean:
  # This is for the Zwave remotes only
  guest_bedroom_blinds_mode:
  master_bedroom_blinds_mode:

script:
  blinds_group:
    mode: parallel
    sequence:
      - action: "cover.{{modus}}_cover"
        target:
          entity_id: >
            {% if group == "guest_bedroom" %}
            {{ expand('group.guest_bedroom_blinds') | map(attribute='entity_id') | list}}
            {% elif group == "master_bedroom" %}
            {{ expand('group.master_bedroom_blinds') | map(attribute='entity_id') | list}}
            {% elif group == "dining_room" %}
            {{ expand('group.dining_room_blinds') | map(attribute='entity_id') | list}}
            {% elif group == "office" %}
            {{ expand('group.office_blinds') | map(attribute='entity_id') | list}}
            {% endif %}
      - delay: "00:01:30"
      - action: "cover.{{modus}}_cover"
        target:
          entity_id: >
            {% if group == "guest_bedroom" %}
            {{ expand('group.guest_bedroom_blinds') | map(attribute='entity_id') | list}}
            {% elif group == "master_bedroom" %}
            {{ expand('group.master_bedroom_blinds') | map(attribute='entity_id') | list}}
            {% elif group == "dining_room" %}
            {{ expand('group.dining_room_blinds') | map(attribute='entity_id') | list}}
            {% elif group == "office" %}
            {{ expand('group.office_blinds') | map(attribute='entity_id') | list}}
            {% endif %}
      - delay: "00:00:10"
      - action: homeassistant.update_entity
        target:
          entity_id: >
            {% if group == "guest_bedroom" %}
            {{ expand('group.guest_bedroom_blinds') | map(attribute='entity_id') | list}}
            {% elif group == "master_bedroom" %}
            {{ expand('group.master_bedroom_blinds') | map(attribute='entity_id') | list}}
            {% elif group == "dining_room" %}
            {{ expand('group.dining_room_blinds') | map(attribute='entity_id') | list}}
            {% elif group == "office" %}
            {{ expand('group.office_blinds') | map(attribute='entity_id') | list}}
            {% endif %}

automation:
  - alias: "Lower and Raise Blinds"
    id: "lower_raise_blinds"
    trigger:
      - platform: time
        at: "08:30:00"
        id: morning
      - platform: time
        at: "10:30:00"
        id: morning_later
      - platform: state
        entity_id: sun.sun
        to: below_horizon
        #for: "00:00:00"
        id: sunset
      - platform: state
        entity_id: sun.sun
        to: below_horizon
        for: "00:45:00"
        id: late
    action:
      - choose:
          - conditions: "{{ trigger.id == 'sunset' }}"
            alias: Close Blinds at Sunset
            sequence:
              - action: cover.close_cover
                continue_on_error: true
                target:
                  entity_id:
                    - cover.office_blinds # Christmas -- but maybe not?
                    - cover.guest_bedroom_blinds
                    # Moved from below
                    - cover.office_blinds
                    - cover.dining_room_blinds
                    - cover.master_bedroom_blinds
          # - conditions: "{{ trigger.id == 'late' }}"
          #   alias: Close Blinds Late
          #   sequence:
          #     - action: cover.close_cover
          #       continue_on_error: true
          #       target:
          #         entity_id:
          #           - cover.office_blinds
          #           - cover.dining_room_blinds
          - conditions: "{{ trigger.id == 'morning' }}"
            alias: Open Blinds Morning
            sequence:
              - action: cover.open_cover
                continue_on_error: true
                target:
                  entity_id:
                    - cover.office_blinds
                    - cover.dining_room_blinds
          - conditions: "{{ trigger.id == 'morning_later' }}"
            alias: Open Blinds Morning Later
            sequence:
              # Only open blinds if guest mode is off
              - if: "{{ states('input_boolean.guest_mode') == 'off' }}"
                then:
                  - action: cover.open_cover
                    continue_on_error: true
                    target:
                      entity_id:
                        - cover.guest_bedroom_blinds
                        # - cover.office_blinds # duplicate placeholder

  - alias: "Manually Update Blind State"
    id: manually_update_blind_state
    mode: parallel
    trigger:
      - platform: state
        entity_id: 
          - cover.dining_room_blind_left
          - cover.dining_room_blind_center
          - cover.dining_room_blind_right
          - cover.guest_bedroom_blind_left
          - cover.guest_bedroom_blind_right
          - cover.office_blind_left
          - cover.office_blind_right
          - cover.master_bedroom_blind_left
          - cover.master_bedroom_blind_right
          - cover.master_bathroom_blinds
        to:
          - opening
          - closing
        for: "00:01:30"
    action:
      - action: homeassistant.update_entity
        target:
          entity_id: "{{ trigger.entity_id }}"
      - delay: "00:00:30"
      - action: homeassistant.update_entity
        target:
          entity_id: "{{ trigger.entity_id }}"

  - alias: "Guest Bedroom Blinds with Remote"
    id: guest_bedroom_blinds_remote
    mode: single
    trigger:
      - platform: event
        id: "zwave"
        event_type: zwave_js_value_notification
        event_data:
          # Guest Bedroom
          node_id: 43
          # Hold Down
          value: "KeyHeldDown"
      - platform: event
        id: "zigbee"
        event_type: zha_event
        event_data:
          device_ieee: cc:86:ec:ff:fe:aa:bf:4d
          command: "up_open"
      - platform: event
        id: "zigbee"
        event_type: zha_event
        event_data:
          device_ieee: cc:86:ec:ff:fe:aa:bf:4d
          command: "down_close"
    action:
      - if: "{{ trigger.id == 'zwave' }}"
        then:
          - action: cover.stop_cover
            target:
              entity_id: cover.guest_bedroom_blinds
          - action: "cover.{% if is_state('input_boolean.guest_bedroom_blinds_mode', 'on') %}close{% else %}open{% endif %}_cover"
            target:
              entity_id: cover.guest_bedroom_blinds
          - action: input_boolean.toggle
            entity_id: input_boolean.guest_bedroom_blinds_mode
          - delay: "00:00:02"
      - if: "{{ trigger.id == 'zigbee' }}"
        then:
          - action: "cover.{% if trigger.event.data.command == 'down_close' %}close{% elif trigger.event.data.command == 'up_open' %}open{% endif %}_cover"
            target:
              entity_id: cover.guest_bedroom_blinds
