# Don't forget to uncomment references to Christmas in Appdaemon apps.yaml
# also check NodeRed and updare appropriately (front sconces and porch lights)

automation:
  - alias: "315Mhz Remote"
    id: "315mhz_remote"
    trigger:
      - platform: mqtt
        topic: "sensor/rtl_433_test"
        value_template: "{{ value_json.model }}"
        payload: "Smoke-GS558"
    action:
      action: >
        {% if trigger.payload_json.code == "87f7b0" %}
          homeassistant.turn_on
        {% elif trigger.payload_json.code == "67f7b0" %}
          homeassistant.turn_off
        {% endif %}
      entity_id: group.christmas_trees

group:
  ###
  # In group.yaml be sure to also uncomment:
  #  - group.christmas 
  #  - switch.dining_room_christmas_tree
  #  - switch.office_christmas_tree
  ###
  christmas:
    name: Christmas
    entities:
      # Christmas lights (outdoor) are handled by Appdaemon alone
      - group.christmas_trees
      - switch.ferris_wheel
      - switch.santa_tree
      - switch.nativity
      - switch.christmas_picture
      - switch.christmas_fena_s_village

  christmas_trees:
    entities:
      # - switch.dining_room_christmas_tree # Leave Commented -- On follows other trees via appdaemon, on timer via appdaemon, off via group.off_at_bedtime OR timer
      # - switch.office_christmas_tree # Leave Commented -- On follows other trees via appdaemon, on timer via appdaemon, off via group.off_at_bedtime OR timer
      # - switch.master_bedroom_christmas_tree # Leave Commented -- On follows other trees via appdaemon
      - switch.kitchen_christmas_tree
      - switch.living_room_christmas_tree

script:
  ### 
  # Be sure to also uncomment references to christmas in scripts.yaml
  ###
  christmas_goodnight:
    mode: 'restart'
    # Play Christmas music, say goodnight, fade music out, and turn off tree
    sequence:
      - action: switch.turn_on
        entity_id: switch.master_bedroom_christmas_tree
      - action: media_player.select_source
        data:
          entity_id: media_player.spotify
          source: "Master"
      - delay: '00:00:03'
      - action: media_player.volume_set
        data:
          entity_id: media_player.spotify
          volume_level: 0.50
      # - action: media_player.shuffle_set
      #   data:
      #     shuffle: true
      #     entity_id: media_player.spotify
      - action: media_player.play_media
        data:
          media_content_id: spotify:track:3XsaSIPWvM61RIFfeb0BBR
          media_content_type: music
          entity_id: media_player.spotify
      - delay: "00:00:05"
      - action: media_player.volume_set
        data:
          entity_id: media_player.spotify
          volume_level: 0.50
      - delay: "00:01:35" # Don't play the whole song
      - action: notify.alexa_media_master
        data:
          data:
            type: tts
            method: speak
          message: "<prosody rate='65%'><amazon:emotion name='excited' intensity='low'>And to all a good night</amazon:emotion></prosody>"
      - delay: '00:00:05'
      - action: switch.turn_off
        entity_id: switch.master_bedroom_christmas_tree
      # Fade music out
      - repeat:
          while: "{{ state_attr('media_player.spotify', 'volume_level') > 0 }}"
          sequence:
            - action: media_player.volume_set
              data_template:
                entity_id: media_player.spotify
                volume_level: >
                  {{ state_attr('media_player.spotify', 'volume_level') - 0.02 }}
            - delay:
                seconds: 0.4
      - action: media_player.media_pause
        data_template:
          entity_id: media_player.spotify

  christmas_wakeup:
    mode: 'restart'
    sequence:
      - action: switch.turn_on
        entity_id: switch.master_bedroom_christmas_tree
      - action: media_player.select_source
        data:
          entity_id: media_player.spotify
          source: "Master"
      - delay: '00:00:03'
      - action: media_player.volume_set
        data:
          entity_id: media_player.spotify
          volume_level: 0.40
      - action: media_player.play_media
        data:
          media_content_id: spotify:track:6cgDUe244IMHFGLqg9A2hD
          media_content_type: music
          entity_id: media_player.spotify
      - delay: "00:00:05"
      - action: media_player.volume_set
        data:
          entity_id: media_player.spotify
          volume_level: 0.40
      - delay: '00:02:12'
      - action: media_player.media_pause
        data_template:
          entity_id: media_player.spotify