# Cloudflare worker calls this autmation via webhook.
# Worker code at extras/door_otp_worker.js

automation:
  - alias: "Set Garage Exterior Door OTP"
    id: set_garage_otp
    mode: restart
    trigger:
      - platform: webhook
        webhook_id: !secret cf_lock_otp_webhook
        local_only: false
    action:
      - action: zwave_js.clear_lock_usercode
        entity_id: lock.garage_exterior_door
        data:
          code_slot: 30
      - action: notify.signal_homeassistant
        data:
          message: "Garage code {{ trigger.json['otp'] }} generated for {{ trigger.json['email'] }}"
      - action: zwave_js.set_lock_usercode
        data:
          entity_id: lock.garage_exterior_door
          code_slot: 30
          usercode: "{{ trigger.json['otp'] }}"
      - action: switch.turn_on
        entity_id: switch.garage_exterior_light
      - delay: 60
      - action: zwave_js.clear_lock_usercode
        entity_id: lock.garage_exterior_door
        data:
          code_slot: 30
      - action: switch.turn_off
        entity_id: switch.garage_exterior_light
