# switch.irrigation_24v_power                  Sprinklers 24v Power                  on       2020-09-29T12:32:44.866660+00:00
# switch.irrigation_front_beds                 Sprinklers Front Beds                 off      2020-09-29T12:32:44.915536+00:00
# switch.irrigation_front_lawn                 Sprinklers Front Lawn                 off      2020-09-29T12:32:44.915887+00:00
# switch.irrigation_left_and_main_rear_lawn    Sprinklers Left and Main Rear Lawn    off      2020-09-29T12:32:44.921695+00:00
# switch.irrigation_front_and_right_rear_lawn  Sprinklers Front and Right Rear Lawn  off      2020-09-29T12:32:44.932068+00:00
# switch.irrigation_side_lawn                  Sprinklers Side Lawn                  off      2020-09-29T12:32:44.949961+00:00
# switch.irrigation_zone_6                     Sprinklers Zone 6                     off      2020-09-29T12:32:44.969619+00:00
# switch.irrigation_zone_7                     Sprinklers Zone 7                     off      2020-09-29T12:32:44.986757+00:00
# switch.irrigation_master_valve               Sprinklers Master Valve               off      2020-09-29T12:32:45.118323+00:00

# Also see NodeRED
# Also see python_scripts/irrigation_custom_water.py

input_boolean:
  front_bed_irrigation_scheduling:
    name: Front Bed Irrigation Auto Run
    icon: mdi:clock-time-two-outline

  lawn_irrigation_scheduling:
    name: Lawn Irrigation Auto Run
    icon: mdi:clock-time-two-outline

  irrigation_force_run:
    name: "Force Scheduled Run"
    icon: "mdi:sprinkler-variant"

  irrigation_rain_forecast_delay:
    name: "Irrigation Forecasted Rain Delay"
    icon: "mdi:cloud-percent"

  irrigation_rainfall_delay:
    name: "Irrigation Rainfall Delay"
    icon: "mdi:weather-pouring"

  irrigation_wind_delay:
    name: "Irrigation Wind Delay"
    icon: "mdi:weather-windy"

input_datetime:
  bhyve_1_last_start: 
    name: Irrigation Bhyve 1 Last Start Time 
    has_date: true
    has_time: true
  bhyve_1_last_stop: 
    name: Irrigation Bhyve 1 Last Stop Time 
    has_date: true
    has_time: true

  bhyve_2_last_start: 
    name: Irrigation Bhyve 2 Last Start Time 
    has_date: true
    has_time: true
  bhyve_2_last_stop: 
    name: Irrigation Bhyve 3 Last Stop Time 
    has_date: true
    has_time: true

  bhyve_3_last_start: 
    name: Irrigation Bhyve 3 Last Start Time 
    has_date: true
    has_time: true
  bhyve_3_last_stop: 
    name: Irrigation Bhyve 3 Last Stop Time 
    has_date: true
    has_time: true

  irrigation_front_beds_last_start: 
    name: Sprinkler Front Beds Last Start Time 
    has_date: true
    has_time: true
  irrigation_front_beds_last_stop: 
    name: Sprinkler Front Beds Last Stop Time 
    has_date: true
    has_time: true
    
  irrigation_front_lawn_last_start: 
    name: Sprinkler Front Lawn Last Start Time 
    has_date: true
    has_time: true
  irrigation_front_lawn_last_stop: 
    name: Sprinkler Front Lawn Last Stop Time 
    has_date: true
    has_time: true
    
  irrigation_left_and_main_rear_lawn_last_start: 
    name: Sprinkler Left and Main Rear Lawn Last Start Time 
    has_date: true
    has_time: true
  irrigation_left_and_main_rear_lawn_last_stop: 
    name: Sprinkler Left and Main Rear Lawn Last Stop Time 
    has_date: true
    has_time: true
    
  irrigation_front_and_right_rear_lawn_last_start: 
    name: Sprinkler Front and Right Rear Lawn Last Start Time 
    has_date: true
    has_time: true
  irrigation_front_and_right_rear_lawn_last_stop: 
    name: Sprinkler Front and Right Rear Lawn Last Stop Time 
    has_date: true
    has_time: true
    
  irrigation_side_lawn_last_start: 
    name: Sprinkler Side Lawn Last Start Time 
    has_date: true
    has_time: true
  irrigation_side_lawn_last_stop: 
    name: Sprinkler Side Lawn Last Stop Time 
    has_date: true
    has_time: true

  irrigation_master_valve_last_start: 
    name: Sprinkler Master Valve Last Start Time 
    has_date: true
    has_time: true
  irrigation_master_valve_last_stop: 
    name: Sprinkler Master Valve Last Stop Time 
    has_date: true
    has_time: true

# Used by python_script and Node Red to make a custom water cycle
input_select:
  irrigation_custom_water_1:
    name: Custom Water 1
    # initial: None
    options:
      - Front Beds
      - Front Lawn
      - Left and Main Rear Lawn
      - Front and Right Rear Lawn
      - Side Lawn
      - None

  irrigation_custom_water_2:
    name: Custom Water 2
    # initial: None
    options:
      - Front Beds
      - Front Lawn
      - Left and Main Rear Lawn
      - Front and Right Rear Lawn
      - Side Lawn
      - None

  irrigation_custom_water_3:
    name: Custom Water 3
    # initial: None
    options:
      - Front Beds
      - Front Lawn
      - Left and Main Rear Lawn
      - Front and Right Rear Lawn
      - Side Lawn
      - None

  irrigation_custom_water_4:
    name: Custom Water 4
    # initial: None
    options:
      - Front Beds
      - Front Lawn
      - Left and Main Rear Lawn
      - Front and Right Rear Lawn
      - Side Lawn
      - None

  irrigation_custom_water_5:
    name: Custom Water 5
    # initial: None
    options:
      - Front Beds
      - Front Lawn
      - Left and Main Rear Lawn
      - Front and Right Rear Lawn
      - Side Lawn
      - None

input_text:
  lawn_irrigation_reason:
    name: Lawn Irrigation Override Reason
    initial: None

  front_bed_irrigation_reason:
    name: Front Bed Irrigation Override Reason
    initial: None

mqtt:
  sensor:
    - name: "Irrigation Time Remaining"
      state_topic: "sensor/irrigation_time_remaining"

automation:
  - alias: B-hyve next watering & rain delay finishing updater
    trigger:
      - platform: state
        entity_id: 
          - switch.bhyve_1
          # - switch.bhyve_2
          # - switch.bhyve_3
      - platform: homeassistant
        event: start
    action:
      - service: python_script.bhyve_next_watering
        data:
          entity_id: switch.bhyve_1
      # - service: python_script.bhyve_next_watering
      #   data:
      #     entity_id: switch.bhyve_2
      # - service: python_script.bhyve_next_watering
      #   data:
      #     entity_id: switch.bhyve_3

  - alias: Store Sprinkler Start/Stop Times
    id: "store_sprinkler_times"
    initial_state: on
    mode: parallel
    trigger:
      platform: state
      entity_id:
        - switch.bhyve_1
        - switch.bhyve_2
        - switch.bhyve_3
        - switch.irrigation_front_beds
        - switch.irrigation_front_lawn 
        - switch.irrigation_left_and_main_rear_lawn
        - switch.irrigation_front_and_right_rear_lawn
        - switch.irrigation_side_lawn
        - switch.irrigation_master_valve
      from: "off"
      to: "on"
      for: "00:00:30"
    action:
      - service: input_datetime.set_datetime
        data:
          entity_id: "input_datetime.{{ trigger.entity_id |regex_replace(find='switch.', replace='', ignorecase=False) }}_last_start"
          time: "{{ ((as_timestamp(now()) - 30) | timestamp_custom('%H:%M:%S', true)) }}"
          date: "{{ (as_timestamp(now()) | timestamp_custom('%Y-%m-%d', true)) }}"
      - wait_template: "{{ is_state(trigger.entity_id, 'off') }}"
        timeout:
          minutes: 60
        continue_on_timeout: false
      - service: input_datetime.set_datetime
        data:
          entity_id: "input_datetime.{{ trigger.entity_id |regex_replace(find='switch.', replace='', ignorecase=False) }}_last_stop"
          time: "{{ ((as_timestamp(now())) | timestamp_custom('%H:%M:%S', true)) }}"
          date: "{{ (as_timestamp(now()) | timestamp_custom('%Y-%m-%d', true)) }}"