# sensor:
#   # Gate
#   - platform: mqtt
#     state_topic: "mom_and_dad/sensor/gate_battery_voltage/state"
#     name: gate_battery_voltage
#     unit_of_measurement: 'V'
#   - platform: mqtt
#     state_topic: "mom_and_dad/sensor/ip_address/state"
#     name: gate_ip_address
#   - platform: mqtt
#     state_topic: "mom_and_dad/sensor/gate_movement_cause/state"
#     name: gate_movement_cause
#   - platform: mqtt
#     state_topic: "mom_and_dad/sensor/uptime/state"
#     name: gate_uptime
#     unit_of_measurement: 's'
#   - platform: mqtt
#     state_topic: "mom_and_dad/status"
#     name: gate_online_offline

#   # Garage
#   - platform: mqtt
#     state_topic: "mom_and_dad_garage/sensor/ip_address/state"
#     name: mom_and_dad_garage_ip_address
#   - platform: mqtt
#     state_topic: "mom_and_dad_garage/sensor/uptime/state"
#     name: mom_and_dad_garage_uptime
#     unit_of_measurement: 's'

# cover:
#   - platform: mqtt
#     name: "Mom and Dad Garage"
#     availability:
#       - topic: "mom_and_dad_garage/status"
#     command_topic: "cmd/mom_and_dad_garage"
#     state_topic: "mom_and_dad_garage/cover/garage_door/state"
#     qos: 0
#     retain: false
#     optimistic: false

# binary_sensor:
#   - platform: mqtt
#     state_topic: "mom_and_dad/binary_sensor/gate_status/state"
#     name: gate_status
#     device_class: door

#   - platform: mqtt
#     state_topic: "mom_and_dad/binary_sensor/heading_comparison_trigger/state"
#     name: gate_heading_comparison

#   - platform: mqtt
#     state_topic: "mom_and_dad/binary_sensor/automation_safety/state"
#     name: gate_automation_safety

automation:
  # - alias: "Gate Heading Comparison Action Notify"
  #   id: "gate_heading_notify"
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.gate_automation_safety
  #       to: 'on'
  #   action:
  #     - action: notify.pushover
  #       data:
  #         message: >
  #           Vehicle Sensor Automation Fired!

  - alias: "IFTTT Webhook Trigger Magnolia"
    id: "ifttt_webhook_trigger_magnolia"
    mode: "single"
    initial_state: "on"
    trigger:
      - platform: webhook
        webhook_id: !secret mom_and_dad_gate_webhook_id
        local_only: false
        id: gate
        allowed_methods: 
          - GET
      - platform: webhook
        webhook_id: !secret mom_and_dad_garage_webhook_id
        local_only: false
        id: garage
        allowed_methods: 
          - GET
    action:
      - action: cover.toggle
        data:
          entity_id: >
            {% if trigger.id == 'gate' %}
              cover.mom_and_dad_gate_mom_and_dad_gate
            {% elif trigger.id == 'garage' %}
              cover.mom_and_dad_garage_mom_and_dad_garage
            {% endif %}
      - delay: "00:00:05"

  # - alias: "Worker Trigger Magnolia"
  #   id: "webhook_trigger_magnolia"
  #   mode: "single"
  #   initial_state: "on"
  #   trigger:
  #     - platform: webhook
  #       webhook_id: !secret cf_otp_webhook_gate
  #       local_only: false
  #       id: gate
  #     - platform: webhook
  #       webhook_id: !secret cf_otp_webhook_garage
  #       local_only: false
  #       id: garage
  #   action:
  #     - action: cover.toggle
  #       data:
  #         entity_id: >
  #           {% if trigger.id == 'gate' %}
  #             cover.mom_and_dad_gate_mom_and_dad_gate
  #           {% elif trigger.id == 'garage' %}
  #             cover.mom_and_dad_garage_mom_and_dad_garage
  #           {% endif %}
  #     - action: notify.signal_self
  #       data:
  #         message: "Mom and Dad {% if trigger.id == 'gate' %}gate{% elif trigger.id == 'garage' %}garage{% endif %} toggled by {{ trigger.json['email'] }}"
