# https://gist.github.com/aneisch/15fa9691ce95431f9be155a432514304

automation:
  - alias: "Start Fotoo"
    id: start_fotoo
    mode: "parallel"
    trigger:
      - platform: state
        entity_id: 
          - media_player.office_photo_frame
          - media_player.kitchen_photo_frame
          - media_player.misc_photo_frame
        from: 
          - "unavailable"
          - "unknown"
    action:
      - if: "{{ trigger.to_state.state != 'off' }}"
        then:
          - action: script.photo_frame_launch_fotoo
            data:
              entity_id: "{{ trigger.entity_id }}"

  - alias: "Photo Frames on when MacBook Active"
    id: "photo_frames_macbook_active"
    initial_state: on
    trigger:
      platform: state
      entity_id: binary_sensor.weasel_active
      to: "on"
    condition: "{{ states('person.andrew') == 'home' }}"
    action:
      - action: homeassistant.turn_on
        entity_id:
        - switch.andrew_monitor
        - media_player.kitchen_photo_frame
        - media_player.office_photo_frame
      # Only turn on guest bathroom frame if guest mode
      - if: "{{ is_state('input_boolean.guest_mode', 'on') }}"
        then:
          - action: media_player.turn_on
            entity_id: 
              - media_player.misc_photo_frame

script:
  photo_frame_launch_fotoo:
    mode: "parallel"
    sequence:
      - action: androidtv.adb_command
        target:
          entity_id: "{{ entity_id }}"
        data:
          command: "am start com.bo.fotoo/com.bo.fotoo.ui.home.FTHomeActivity"

  # photo_frame_launch_ha_dashboard:
  #   mode: 'restart'
  #   sequence:
  #     - action: androidtv.adb_command
  #       target:
  #         entity_id: media_player.kitchen_photo_frame
  #       data:
  #         command: "am start -a android.intent.action.VIEW -d 'http://10.0.1.22:8123'" # Fully Kiosk
  #     - delay: "00:30:00"
  #     - action: script.photo_frame_launch_fotoo
  #       data:
  #         entity_id: "{{ entity_id }}"

  # photo_frame_launch_spotify:
  #   mode: 'restart'
  #   sequence:
  #     - action: androidtv.adb_command
  #       target:
  #         entity_id: "{{ entity_id }}"
  #       data:
  #         command: "am start com.spotify.music"
  #     - delay: "{{ delay | default('00:30:00')}}" # If we launch it manually, time out after 30 minutes by default. Override by passing delay to this service
  #     - action: script.photo_frame_launch_fotoo
  #       data:
  #         entity_id: "{{ entity_id }}"

  photo_frame_launch_mealie:
    mode: 'restart'
    sequence:
      - action: androidtv.adb_command
        target:
          entity_id: media_player.kitchen_photo_frame
        data:
          command: "am start -a android.intent.action.VIEW -d 'http://recipes.home.secret'" # Fully Kiosk

  photo_frame_launch_front_door_stream:
    mode: 'single'
    sequence:
      - action: androidtv.adb_command
        target:
          entity_id: "{{ entity_id }}"
        data:
          # https://xdaforums.com/t/how-to-load-full-desktop-websites-permanently-in-chrome-for-android.3771982/post-78875887
          command: "am start -a com.google.android.apps.chrome.ACTION_CLOSE_TABS -n com.android.chrome/org.chromium.chrome.browser.ChromeTabbedActivity"
      - action: androidtv.adb_command
        target:
          entity_id: "{{ entity_id }}"
        data:
          #command: "am start -a android.intent.action.VIEW -d 'http://10.0.1.22:8123/api/camera_proxy_stream/camera.front_door_test?token={{ state_attr('camera.front_door_test','access_token')}}'"
          command: "am start -n com.android.chrome/com.google.android.apps.chrome.Main -a android.intent.action.VIEW -d 'https://frigate.home.secret/live/webrtc/webrtc.html?src=front_door'"
      - delay: "00:00:05"
      - action: androidtv.adb_command
        target:
          entity_id: "{{ entity_id }}"
        data:
          command: "input tap 200 200" # Random Tap
      - action: androidtv.adb_command
        target:
          entity_id: "{{ entity_id }}"
        data:
          command: "input tap 1850 1033" # Full Screen
      # - action: androidtv.adb_command
      #   target:
      #     entity_id: "{{ entity_id }}"
      #   data:
      #     command: "input tap 1760 1033" # Unmute
      # - action: androidtv.adb_command
      #   target:
      #     entity_id: "{{ entity_id }}"
      #   data:
      #     command: "input tap 1760 1033" # Unmute
      - delay: "{{ delay | default('00:00:30')}}" # If we launch it manually, time out after 30 minutes by default. Override by passing delay to this service
      - action: androidtv.adb_command
        target:
          entity_id: "{{ entity_id }}"
        data:
          # https://xdaforums.com/t/how-to-load-full-desktop-websites-permanently-in-chrome-for-android.3771982/post-78875887
          command: "am start -a com.google.android.apps.chrome.ACTION_CLOSE_TABS -n com.android.chrome/org.chromium.chrome.browser.ChromeTabbedActivity"
      # In case we were showing timers before..
      - delay: "00:00:01"
      - if: "{{ is_state('input_boolean.kitchen_timers_showing','on') }}"
        then:
          - action: script.photo_frame_launch_timers
            data:
              entity_id: 
                - media_player.kitchen_photo_frame
                - media_player.office_photo_frame
        else:
          - action: script.photo_frame_launch_fotoo
            data:
              entity_id: "{{ entity_id }}"

  photo_frame_launch_url:
    mode: 'restart'
    sequence:
      - action: androidtv.adb_command
        target:
          entity_id: "{{ entity_id }}"
        data:
          command: "am start -a android.intent.action.VIEW -d '{{ states('input_text.kitchen_frame_url') }}'"
      - delay: "{{ delay | default('00:30:00')}}" # Time out after 30 minutes by default. Override by passing delay to this service
      - action: script.photo_frame_launch_fotoo
        data:
          entity_id: "{{ entity_id }}"

  photo_frame_launch_timers:
    mode: 'restart'
    sequence:
      - action: androidtv.adb_command
        target:
          entity_id: "{{ entity_id }}"
        data:
          # https://xdaforums.com/t/how-to-load-full-desktop-websites-permanently-in-chrome-for-android.3771982/post-78875887
          command: "am start -a com.google.android.apps.chrome.ACTION_CLOSE_TABS -n com.android.chrome/org.chromium.chrome.browser.ChromeTabbedActivity"
      - action: androidtv.adb_command
        target:
          entity_id: "{{ entity_id }}"
        data:
          command: "am start -n com.android.chrome/com.google.android.apps.chrome.Main -a android.intent.action.VIEW -d 'http://10.0.1.22:8123/lovelace/timers?wp_enabled=true'"
      - delay: "00:00:15"
      - action: androidtv.adb_command
        target:
          entity_id: "{{ entity_id }}"
        data:
          command: "input tap 50 200" # tap on screen to make fullscreen