automation:
  - alias: "Smoke Alarm Secondary"
    id: "smoke_alarm_secondary"
    initial_state: on
    trigger:
      platform: state
      entity_id:
        - binary_sensor.office_alarm_co_alarm_alarm_silenced
        - binary_sensor.office_alarm_co_alarm_carbon_monoxide_detected
        - binary_sensor.office_alarm_co_alarm_replacement_required_end_of_life
        - binary_sensor.office_alarm_smoke_alarm_alarm_silenced
        - binary_sensor.office_alarm_system_system_hardware_failure
        - binary_sensor.hallway_alarm_co_alarm_alarm_silenced
        - binary_sensor.hallway_alarm_co_alarm_carbon_monoxide_detected
        - binary_sensor.hallway_alarm_co_alarm_replacement_required_end_of_life
        - binary_sensor.hallway_alarm_smoke_alarm_alarm_silenced
        - binary_sensor.hallway_alarm_system_system_hardware_failure
        - binary_sensor.hardwired_smoke_alarms_carbon_monoxide_detected
      from: "off"
      to: "on"
    action:
      - service: script.notify_wrapper
        data:
          message: "{{ trigger.from_state.attributes.friendly_name }}"

  # - alias: "Smoke Alarm Battery Alerts"
  #   id: "smoke_alarm_battery_alert"
  #   trigger:
  #     - platform: numeric_state
  #       entity_id:
  #         - sensor.hallway_alarm_battery_level
  #         - sensor.office_alarm_battery_level
  #       below: 79
  #   action:
  #     - service: script.notify_wrapper
  #       data:
  #         message: "{{ trigger.to_state.name }} battery level at {{ trigger.to_state.state }}%. Time to replace!"

  - alias: "Smoke Alarm Detection"
    id: "smoke_alarm_detection"
    initial_state: on
    trigger:
      platform: state
      entity_id:
        - binary_sensor.office_alarm_smoke_alarm_smoke_alarm_test
        - binary_sensor.office_alarm_smoke_alarm_smoke_detected
        - binary_sensor.hallway_alarm_smoke_alarm_smoke_alarm_test
        - binary_sensor.hallway_alarm_smoke_alarm_smoke_detected
        - binary_sensor.hardwired_smoke_alarms_smoke_detected
      from: "off"
      to: "on"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.smoke_alarm_triggered
      - service: script.notify_wrapper
        data:
          message: >
            {{ trigger.from_state.attributes.friendly_name }}: Triggered
          data:
            priority: 2
      - service: climate.turn_off
        entity_id: climate.thermostat

  - alias: "Smoke Alarm Clear"
    id: "smoke_alarm_clear"
    initial_state: on
    trigger:
      platform: state
      entity_id:
        - binary_sensor.office_alarm_smoke_alarm_smoke_alarm_test
        - binary_sensor.office_alarm_smoke_alarm_smoke_detected
        - binary_sensor.hallway_alarm_smoke_alarm_smoke_alarm_test
        - binary_sensor.hallway_alarm_smoke_alarm_smoke_detected
        - binary_sensor.hardwired_smoke_alarms_smoke_detected
      from: "on"
      to: "off"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.smoke_alarm_triggered
      - service: script.notify_wrapper
        data:
          message: >
            {{ trigger.from_state.attributes.friendly_name }}: Cleared. Turn A/C on manually.
          data:
            priority: 1
      # - service: climate.turn_on
      #   entity_id: climate.thermostat

  - alias: "Smoke Alarm Home Response"
    id: "smoke_alarm_home_response"
    initial_state: on
    trigger:
      platform: state
      entity_id:
        - input_boolean.smoke_alarm_triggered
      to: "on"
    action:
      # If sun down, turn on some lights
      - if: "{{ states('sun.sun') == 'below_horizon' }}"
        then:
          - alias: "Turn on some Lights"
            service: homeassistant.turn_on
            data:
              brightness: 255
              transition: 5
            target:
              entity_id:
                - light.master_bedroom_lamps
                - light.kitchen_can_lights
                - light.living_room_can_lights

# script:
#   smoke_alarm_trigger_response:
#     sequence:
#       - service: homeassistant.turn_on
#         data:
#           entity_id: input_boolean.security_status
#       - service: homeassistant.turn_off
#         data:
#           entity_id: group.master_bedroom
#       - service: homeassistant.turn_off
#         data:
#           entity_id: group.common_areas

#   smoke_alarm_clear_response:
#     sequence:
#       - service: homeassistant.turn_on
#         data:
#           entity_id: input_boolean.security_status
#       - service: homeassistant.turn_off
#         data:
#           entity_id: group.master_bedroom
#       - service: homeassistant.turn_off
#         data:
#           entity_id: group.common_areas

input_boolean:
  smoke_alarm_triggered:
    name: Smoke Alarm Triggered
