# Vacuum set up in GUI: https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor
# See also: ../python_scripts/vacuum_custom_clean.py that allows custom room clean

automation:
  - id: vacuum-update-map-extractor-camera
    alias: Vacuum - Update Map Extractor camera
    description: ""
    use_blueprint:
      path: PiotrMachowski/update_map_extractor.yaml
      input:
        vacuum: vacuum.roborock_s4
        camera: camera.xiaomi_cloud_map_extractor
        mode_to_handle: turn_off_when_docked
        update_once_after_docking: true
        #browser_mod_path: /lovelace/vacuum

  - alias: "Vacuum Map at Restart"
    id: "vacuum_map_startup"
    initial_state: on
    trigger:
      - platform: homeassistant
        event: start
    action:
      - action: camera.turn_on
        entity_id: camera.xiaomi_cloud_map_extractor
      - delay: "00:00:30"
      - action: camera.turn_off
        entity_id: camera.xiaomi_cloud_map_extractor

  - alias: "Roborock Go to Trashcan After Cleaning"
    id: "roborock_to_trashcan"
    trigger:
      - platform: state
        entity_id: vacuum.roborock_s4
        to: "returning"
    condition:
      condition: state
      entity_id: input_boolean.return_to_trashcan
      state: "on"
    action:
      - action: vacuum.pause
        entity_id: vacuum.roborock_s4
      - delay: "00:00:02"
      - action: script.vacuum_park_trashcan
      - action: homeassistant.turn_off
        entity_id: input_boolean.return_to_trashcan

  - alias: "Vacuum When House Unoccupied"
    id: "vacuum_house_unoccupied"
    initial_state: off
    trigger:
      - platform: state
        entity_id: group.trackers
        to: not_home
    action:
      - action: python_script.vacuum_custom_clean
      - action: homeassistant.turn_off
        entity_id: automation.vacuum_when_house_unoccupied

  - alias: "Vacuum Kitchen With Button"
    id: "vacuum_kitchen_button"
    initial_state: on
    trigger:
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          # Kitchen Sink Button
          node_id: 3
          # Hold Down
          value: "KeyHeldDown"
    action:
      - action: script.vacuum_clean_kitchen
      - action: notify.alexa_media_kitchen
        data:
          data:
            type: tts
          message: "Sending Roxie to clean the Kitchen"

  - alias: "Pause Vacuum When Timer Expires"
    id: pause_vacuum_timer_expire
    trigger:
      - platform: state
        entity_id: sensor.kitchen_timer_countdown
        to: "Expired"
    condition: '{{ states("vacuum.roborock_s4") == "cleaning" }}'
    action:
      - action: vacuum.pause
        entity_id: vacuum.roborock_s4
      - wait_template: "{{ states('sensor.kitchen_timer_countdown') != 'Expired' }}"
        timeout: "00:01:30"
      - action: vacuum.start
        entity_id: vacuum.roborock_s4

sensor:
  - platform: template
    sensors:
      roborock_s4_battery:
        friendly_name: "Roborock S4 Battery"
        value_template: "{{state_attr('vacuum.roborock_s4', 'battery_level')}}"
        unit_of_measurement: "%"
        device_class: battery

      # roborock_s4_lifetime_cleaned_area:
      #   friendly_name: 'Lifetime Cleaned Area'
      #   value_template: "{{state_attr('vacuum.roborock_s4', 'total_cleaned_area')}}"
      #   unit_of_measurement: ㎡

      # roborock_s4_lifetime_cleaning_time:
      #   friendly_name: 'Lifetime Cleaning Time'
      #   value_template: "{{(state_attr('vacuum.roborock_s4', 'total_cleaning_time') / 60)|round(1, 'floor')}}"

      # NOTE: This date is converted to be timezone aware so that it plays nice
      # with some other templating functions and filters.
      roborock_s4_last_cleaned:
        friendly_name: Relative time since last cleaning ended
        value_template: "{{time_since(strptime(as_timestamp(states('sensor.roborock_s4_last_clean_end'))|timestamp_custom('%Y-%m-%d %H:%M:%S'), '%Y-%m-%d %H:%M:%S'))}}"

      # roborock_s4_lifetime_cleaning_count:
      #   friendly_name: 'Lifetime Cleaning Count'
      #   value_template: "{{state_attr('vacuum.roborock_s4', 'cleaning_count')}}"

      # # Used for the Filter maintenance card
      # roborock_s4_filter_remaining:
      #   friendly_name: '% Filter Remaining'
      #   unit_of_measurement: '%'
      #   value_template: "{{((state_attr('vacuum.roborock_s4', 'filter_left') / 150) * 100) | round | int}}"

      # # Used for the Filter maintenance card
      # roborock_s4_filter_hrs_remaining:
      #   friendly_name: 'Filter Remaining Hours'
      #   unit_of_measurement: 'hrs'
      #   value_template: "{{state_attr('vacuum.roborock_s4', 'filter_left')}}"

      # # Used for the Side Brush maintenance card
      # roborock_s4_side_brush_remaining:
      #   friendly_name: '% Side Brush Remaining'
      #   unit_of_measurement: '%'
      #   value_template: "{{((state_attr('vacuum.roborock_s4', 'side_brush_left') / 200) * 100) | round | int}}"

      # # Used for the Side Brush maintenance card
      # roborock_s4_side_brush_hrs_remaining:
      #   friendly_name: 'Side Brush Remaining Hours'
      #   unit_of_measurement: 'hrs'
      #   value_template: "{{state_attr('vacuum.roborock_s4', 'side_brush_left')}}"

      # # Used for the Main Brush maintenance card
      # roborock_s4_main_brush_remaining:
      #   friendly_name: '% Main Brush Remaining'
      #   unit_of_measurement: '%'
      #   value_template: "{{((state_attr('vacuum.roborock_s4', 'main_brush_left') / 300) * 100) | round | int}}"

      # # Used for the Main Brush maintenance card
      # roborock_s4_main_brush_hrs_remaining:
      #   friendly_name: 'Main Brush Remaining Hours'
      #   unit_of_measurement: 'hrs'
      #   value_template: "{{state_attr('vacuum.roborock_s4', 'main_brush_left')}}"

      # # Used for the Sensors maintenance card
      # roborock_s4_sensors_remaining:
      #   friendly_name: '% Sensors Remaining'
      #   unit_of_measurement: '%'
      #   value_template: "{{((state_attr('vacuum.roborock_s4', 'sensor_dirty_left') / 30) * 100) | round | int}}"

      # # Used for the Sensors maintenance card
      # roborock_s4_sensors_hrs_remaining:
      #   friendly_name: 'Sensors Remaining Hours'
      #   unit_of_measurement: 'hrs'
      #   value_template: "{{state_attr('vacuum.roborock_s4', 'sensor_dirty_left')}}"

      roborock_current_room:
        friendly_name: "Roborock Current Room"
        value_template: >
          {% set room = state_attr('camera.xiaomi_cloud_map_extractor', 'vacuum_room') %}
          {% set lookup = {22: 'Dining Room', 24:'Kitchen', 23:'Living Room', 21: 'Office', 26: 'Guest Bedroom', 19: 'Guest Bathroom', 16: 'Hallway', 20: "Bethany's Office", 18: 'Master Bedroom', 27: 'Master Bathroom', 17: 'Back Bathroom', 25: 'Back Bedroom'} %}
          {% if room != None and room in lookup %}
          {{ lookup[room] }}
          {% else %}
          Dock
          {% endif %}
        attribute_templates:
          segment: "{{ state_attr('camera.xiaomi_cloud_map_extractor', 'vacuum_room') }}"

input_boolean:
  # Nodered
  roborock_daily_run:
    name: Roborock Daily Run
  return_to_trashcan:
    name: Roborock Return to Trashcan After Cleaning
    initial: "off"

input_select:
  vacuum_mode:
    name: Vacuum Clean Mode
    options:
      - Gentle
      - Silent
      - Standard
      - Medium
      - Turbo

  vacuum_room_select:
    name: Choose a room to clean
    # Define these zones in NodeRed
    options:
      - None
      - Dining Room
      - Kitchen
      - Living Room
      - Office
      - Guest Bedroom
      - Guest Bathroom
      - Hallway
      - "Bethany's Office"
      - Master Bedroom
      - Master Bathroom
      - Back Bedroom
      - Back Bathroom

  vacuum_custom_clean_1:
    name: Custom Clean Room 1
    # initial: None
    options:
      - None
      - Dining Room
      - Kitchen
      - Living Room
      - Office
      - Guest Bedroom
      - Guest Bathroom
      - Hallway
      - "Bethany's Office"
      - Master Bedroom
      - Master Bathroom
      - Back Bedroom
      - Back Bathroom

  vacuum_custom_clean_2:
    name: Custom Clean Room 2
    # initial: None
    options:
      - None
      - Dining Room
      - Kitchen
      - Living Room
      - Office
      - Guest Bedroom
      - Guest Bathroom
      - Hallway
      - "Bethany's Office"
      - Master Bedroom
      - Master Bathroom
      - Back Bedroom
      - Back Bathroom

  vacuum_custom_clean_3:
    name: Custom Clean Room 3
    # initial: None
    options:
      - None
      - Dining Room
      - Kitchen
      - Living Room
      - Office
      - Guest Bedroom
      - Guest Bathroom
      - Hallway
      - "Bethany's Office"
      - Master Bedroom
      - Master Bathroom
      - Back Bedroom
      - Back Bathroom

  vacuum_custom_clean_4:
    name: Custom Clean Room 4
    # initial: None
    options:
      - None
      - Dining Room
      - Kitchen
      - Living Room
      - Office
      - Guest Bedroom
      - Guest Bathroom
      - Hallway
      - "Bethany's Office"
      - Master Bedroom
      - Master Bathroom
      - Back Bedroom
      - Back Bathroom

  vacuum_custom_clean_5:
    name: Custom Clean Room 5
    # initial: None
    options:
      - None
      - Dining Room
      - Kitchen
      - Living Room
      - Office
      - Guest Bedroom
      - Guest Bathroom
      - Hallway
      - "Bethany's Office"
      - Master Bedroom
      - Master Bathroom
      - Back Bedroom
      - Back Bathroom

  vacuum_custom_clean_6:
    name: Custom Clean Room 6
    # initial: None
    options:
      - None
      - Dining Room
      - Kitchen
      - Living Room
      - Office
      - Guest Bedroom
      - Guest Bathroom
      - Hallway
      - "Bethany's Office"
      - Master Bedroom
      - Master Bathroom
      - Back Bedroom
      - Back Bathroom

  vacuum_custom_clean_7:
    name: Custom Clean Room 7
    # initial: None
    options:
      - None
      - Dining Room
      - Kitchen
      - Living Room
      - Office
      - Guest Bedroom
      - Guest Bathroom
      - Hallway
      - "Bethany's Office"
      - Master Bedroom
      - Master Bathroom
      - Back Bedroom
      - Back Bathroom

  vacuum_custom_clean_8:
    name: Custom Clean Room 8
    # initial: None
    options:
      - None
      - Dining Room
      - Kitchen
      - Living Room
      - Office
      - Guest Bedroom
      - Guest Bathroom
      - Hallway
      - "Bethany's Office"
      - Master Bedroom
      - Master Bathroom
      - Back Bedroom
      - Back Bathroom

  vacuum_custom_clean_9:
    name: Custom Clean Room 9
    # initial: None
    options:
      - None
      - Dining Room
      - Kitchen
      - Living Room
      - Office
      - Guest Bedroom
      - Guest Bathroom
      - Hallway
      - "Bethany's Office"
      - Master Bedroom
      - Master Bathroom
      - Back Bedroom
      - Back Bathroom

  vacuum_custom_clean_10:
    name: Custom Clean Room 10
    # initial: None
    options:
      - None
      - Dining Room
      - Kitchen
      - Living Room
      - Office
      - Guest Bedroom
      - Guest Bathroom
      - Hallway
      - "Bethany's Office"
      - Master Bedroom
      - Master Bathroom
      - Back Bedroom
      - Back Bathroom

script:
  vacuum_follow_path:
    mode: single
    alias: Vacuum follow path
    fields:
      path:
        name: Path
      entity_id:
        name: Vacuum entity
    sequence:
      - repeat:
          count: "{{ path | length }}"
          sequence:
            - choose:
                - conditions: "{{ mode == 'individual' }}"
                  sequence:
                    - action: "{{ service }}"
                      data:
                        entity_id: "{{ entity_id }}"
                        x_coord: "{{ path[repeat.index-1][0] }}"
                        y_coord: "{{ path[repeat.index-1][1] }}"
            - choose:
                - conditions: "{{ mode == 'send_command' }}"
                  sequence:
                    - action: "{{ service }}"
                      data:
                        entity_id: "{{ entity_id }}"
                        command: app_goto_target
                        params: "{{ path[repeat.index-1] }}"
            - wait_template: "{{ is_state(entity_id, 'cleaning') }}"
              timeout: 00:00:30
              continue_on_timeout: false
            - delay: 00:00:01
            - wait_template: "{{ is_state(entity_id, 'idle') or is_state(entity_id, 'paused') }}"
              timeout: 00:05:00
              continue_on_timeout: false

  vacuum_locate:
    sequence:
      - action: vacuum.locate
        entity_id: vacuum.roborock_s4

  vacuum_park_trashcan:
    sequence:
      - action: xiaomi_miio.vacuum_goto
        data:
          entity_id: vacuum.roborock_s4
          x_coord: 13950
          y_coord: 23250

  # For Alexa routines, see python_scripts/vacuum for segment #s
  vacuum_clean_kitchen:
    sequence:
      - action: xiaomi_miio.vacuum_clean_segment
        data:
          entity_id: vacuum.roborock_s4
          segments: 24

  vacuum_clean_living_room:
    sequence:
      - action: xiaomi_miio.vacuum_clean_segment
        data:
          entity_id: vacuum.roborock_s4
          segments: 23

  vacuum_clean_dining_room:
    sequence:
      - action: xiaomi_miio.vacuum_clean_segment
        data:
          entity_id: vacuum.roborock_s4
          segments: 22

  vacuum_clean_office:
    sequence:
      - action: xiaomi_miio.vacuum_clean_segment
        data:
          entity_id: vacuum.roborock_s4
          segments: 21

  vacuum_clean_bethany_office:
    sequence:
      - action: xiaomi_miio.vacuum_clean_segment
        data:
          entity_id: vacuum.roborock_s4
          segments: 20

  vacuum_clean_master_bedroom:
    sequence:
      - action: xiaomi_miio.vacuum_clean_segment
        data:
          entity_id: vacuum.roborock_s4
          segments: 18

  vacuum_clean_guest_bedroom:
    sequence:
      - action: xiaomi_miio.vacuum_clean_segment
        data:
          entity_id: vacuum.roborock_s4
          segments: 26

switch:
  platform: template
  switches:
    # Expose vacuum switch to allow manual turn off via Alexa
    vacuum:
      friendly_name: "Roxie"
      value_template: '{{ is_state("vacuum.roborock_s4", "on") }}'
      turn_on:
        # Dummy, do nothing
        - delay:
            seconds: 1
      turn_off:
        - action: vacuum.stop
          data:
            entity_id: vacuum.roborock_s4
        - delay: "00:00:01"
        - action: vacuum.return_to_base
          data:
            entity_id: vacuum.roborock_s4

camera:
  - platform: xiaomi_cloud_map_extractor
    host: 10.0.0.10
    # https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor
    token: !secret roborock_token
    scan_interval: 10
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ["all"]
    attributes:
      - calibration_points
      - charger
      - cleaned_rooms
      - country
      - goto_path
      - goto_predicted_path
      - goto
      - ignored_obstacles_with_photo
      - ignored_obstacles
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles_with_photo
      - obstacles
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room_name
      - vacuum_room
      - walls
      - zones
    colors:
      color_path: [255, 255, 255]
    map_transformation:
      trim:
        top: 16
        bottom: 15
        left: 10
        right: 15
