#!/bin/bash

message=$(curl -m 40 -s http://10.0.1.29/tstat)

if [[ $message == *-1* ]]
then
exit 1
fi

message_fixed=$(echo $message | sed -e 's/t_heat/setpoint/' -e 's/t_cool/setpoint/')

mosquitto_pub -h 127.0.0.1 -p 1883 -t thermostat -u MQTT_USERNAME -P MQTT_PASSWORD -m $message_fixed
